title: Traces de Passages
description: Un projet éphémère d'interventions artistiques, dans un immeuble centenaire voué à la démolition.
author:
    name: Studio ANDco Sàrl
    twitter: ANDco_o
email: tracesdepassages@gmail.com
lang: fr_CH
logo: tile.png

seo:
    type: Business

street: "Rue du Simplon 26"
city: "Lausanne"
zip: "1006"
state: "Vaud"
country: "Suisse"
latitude: "46.235885"
longitude: "7.3578723"
tel: "078 635 59 66"

social:
  name: Traces de Passages
  links:

twitter:
    username: "Twitter"

facebook:
    app_id: Facebook APP id
    publisher: "https://www.facebook.com/tracesdepassages"

google_site_verification: googleddcee30cf477c8ba
ga: UA-59665695-2

baseurl: ""
url: "https://tracesdepassages.ch"

exclude:

defaults:
  - scope:
      path: ""
    values:
      image: /files/facebook.png

# Build settings
markdown: kramdown
plugins:
    - jekyll-feed
    - jekyll-coffeescript
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-seo-tag
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json

# Github forced settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false

kramdown:
    input: GFM
    hard_wrap: false

collections:
    artistes:
        output: true

    association:
        output: true

# Sitemap

sitemap:
    filename: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"


